program: model_trainer.py
method: bayes
metric:
  goal: minimize
  name: loss
parameters:
  validation_split:
    max: 0.3
    min: 0.05
    distribution: uniform
  batch_size:
    max: 256
    min: 8
    distribution: int_uniform
  epochs:
    max: 10
    min: 3
    distribution: int_uniform
